/*
******************************************************************************
File:     	main.c
Info:     	Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-09-20
Creater:  	Chiao-Shing Lin
Student no:	LNXCHI026

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "tm_stm32f4_dac_signal.h"
#include "stm32f4xx_dac.h"
#include "tm_stm32f4_dma.h"
#include "tm_stm32f4_disco.h"
#include "tm_stm32f4_usb_vcp.h"
/* Private variables */
uint8_t DMAcounter=0;
uint8_t ADCcounter=0;
uint16_t ADCval;
uint8_t ADCval_Split[2];
char done[]="\n";
int numpulses=64;
int numsamples=270976;
uint8_t c;
/* Private function prototypes */
void checkUSB(void);
void SysInit(void);
/* Private functions */
void checkUSB(void){
	if (TM_USB_VCP_Getc(&c) == TM_USB_VCP_DATA_OK) {
		if(c=='1'){
			TM_DISCO_LedOn(LED_BLUE);
			TM_DISCO_LedOn(LED_RED);
			TM_DISCO_LedOn(LED_GREEN);
			TM_DISCO_LedOn(LED_ORANGE);
			DMAcounter=0;
			ADCcounter=0;
			TM_DAC_SIGNAL_Init(TM_DAC1, TIM4);
			ADC_Cmd (ADC1, ENABLE);
			TM_DAC_SIGNAL_SetSignal(TM_DAC1, TM_DAC_SIGNAL_Signal_Chirp, 160000);
			ADC_SoftwareStartConv(ADC1);
			TM_DMA_EnableInterrupts(DAC_SIGNAL_DMA_DAC1_STREAM);
		}
		if(c=='2'){
			TM_DISCO_LedOn(LED_BLUE);
			TM_DISCO_LedOn(LED_RED);
			TM_DISCO_LedOn(LED_GREEN);
			TM_DISCO_LedOn(LED_ORANGE);
			DMAcounter=0;
			ADCcounter=0;
			TM_DAC_SIGNAL_Init(TM_DAC1, TIM4);
			ADC_Cmd (ADC1, ENABLE);
			TM_DAC_SIGNAL_SetSignal(TM_DAC1, TM_DAC_SIGNAL_Signal_Sinus, 160000);
			ADC_SoftwareStartConv(ADC1);
			TM_DMA_EnableInterrupts(DAC_SIGNAL_DMA_DAC1_STREAM);
		}
	}
}

void SysInit(void){
	TM_USB_VCP_Init();
	TM_DISCO_LedInit();

    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);

	GPIO_InitTypeDef      GPIO_InitStructure;
	GPIO_InitStructure.GPIO_Pin =  GPIO_Pin_0;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL ;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	NVIC_InitTypeDef NVIC_InitStruct;

	NVIC_InitStruct.NVIC_IRQChannel = ADC_IRQn;
	NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 1;
	NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
	NVIC_Init(&NVIC_InitStruct);

	ADC_ITConfig(ADC1, ADC_IT_EOC, ENABLE);

	ADC_InitTypeDef       ADC_InitStructure;
	ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;
	ADC_InitStructure.ADC_ScanConvMode = DISABLE;
	ADC_InitStructure.ADC_ContinuousConvMode = ENABLE;
	ADC_InitStructure.ADC_ExternalTrigConv = DISABLE;
	ADC_InitStructure.ADC_ExternalTrigConvEdge = ADC_ExternalTrigConvEdge_None;
	ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
	ADC_InitStructure.ADC_NbrOfConversion = 1;
	ADC_Init(ADC1, &ADC_InitStructure);

	ADC_CommonInitTypeDef ADC_CommonInitStructure;
	ADC_CommonInitStructure.ADC_Mode = ADC_Mode_Independent;
	ADC_CommonInitStructure.ADC_Prescaler = ADC_Prescaler_Div8;
	ADC_CommonInitStructure.ADC_DMAAccessMode = ADC_DMAAccessMode_Disabled;
	ADC_CommonInitStructure.ADC_TwoSamplingDelay = ADC_TwoSamplingDelay_5Cycles;
	ADC_CommonInit(&ADC_CommonInitStructure);
	ADC_RegularChannelConfig(ADC1, ADC_Channel_0, 1, ADC_SampleTime_112Cycles);
}

void ADC_IRQHandler(void){
	ADC_ClearITPendingBit(ADC1, ADC_IT_EOC);
	if (ADCcounter == numsamples){
			TM_USB_VCP_Puts(done);
			ADC_Cmd (ADC1, DISABLE);
		}
	else {
		ADCval = ADC_GetConversionValue(ADC1);
		ADCval_Split[0]=(uint8_t)(ADCval >> 8);
		ADCval_Split[1]=(uint8_t)(ADCval & 0b000011111111);
		TM_USB_VCP_Send(ADCval_Split,2);
		ADCcounter++;
	}
}

void TM_DMA_TransferCompleteHandler(DMA_Stream_TypeDef* DMA_Stream) {
	if (DMAcounter>=numpulses){
		DAC_DeInit();
		TM_DISCO_LedOff(LED_BLUE);
		TM_DISCO_LedOff(LED_RED);
		TM_DISCO_LedOff(LED_GREEN);
		TM_DISCO_LedOff(LED_ORANGE);
	}
	else{
		DMAcounter++;
	}
}


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	SystemInit();
	SysInit();
	while(1){
		checkUSB();
	}
}


